[package]
name = "file-format"
version = "0.14.0"
authors = ["Mickaël Malécot <mickael.malecot@gmail.com>"]
edition = "2021"
description = "Crate for determining the file format of a given file or stream."
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["file-format", "file-type", "magic-number", "media-type", "mime"]
categories = ["filesystem"]
homepage = "https://github.com/mmalecot/file-format"
repository = "https://github.com/mmalecot/file-format"
documentation = "https://docs.rs/file-format"
exclude = ["/.github/*", "/examples/*", "/fixtures/*", "/tests/*"]

[dependencies]
cfb = { version = "0.7", optional = true }
zip = { version = "0.6", optional = true, features = ["deflate-miniz"], default-features = false }

[dependencies.serde]
optional = true
default-features = false
features = [ "derive" ]
version = "1.0"

[features]
## ACCURACY FEATURES

# Enables all accuracy features
accuracy = ["accuracy-mkv", "accuracy-pdf", "accuracy-txt", "accuracy-xml", "accuracy-zip"]
accuracy-mkv = []
accuracy-pdf = []
accuracy-txt = []
accuracy-xml = []
accuracy-zip = []

## READER FEATURES

# Enables all reader features
reader = ["reader-cfb", "reader-exe", "reader-mkv", "reader-pdf", "reader-txt", "reader-xml", "reader-zip"]
reader-cfb = ["dep:cfb"]
reader-exe = []
reader-mkv = []
reader-pdf = []
reader-txt = []
reader-xml = []
reader-zip = ["dep:zip"]

